==> /var/log/alternatives.log <==

==> /var/log/apply_ssh_ratelimit.log <==

==> /var/log/apport.log <==

==> /var/log/auth.log <==
2025-09-09T22:12:51.310622+00:00 eob-250501a sshd[2632]: Disconnected from authenticating user root 117.53.46.76 port 40586 [preauth]
2025-09-09T22:13:24.942879+00:00 eob-250501a CRON[954]: pam_unix(cron:session): session closed for user root
2025-09-09T22:15:01.950014+00:00 eob-250501a CRON[3618]: pam_unix(cron:session): session opened for user root(uid=0) by root(uid=0)
2025-09-09T22:15:01.957098+00:00 eob-250501a CRON[3618]: pam_unix(cron:session): session closed for user root
2025-09-09T22:15:40.691186+00:00 eob-250501a sshd[3631]: Received disconnect from 117.53.46.76 port 57982:11: Bye Bye [preauth]
2025-09-09T22:15:40.693395+00:00 eob-250501a sshd[3631]: Disconnected from authenticating user root 117.53.46.76 port 57982 [preauth]
2025-09-09T22:15:52.082192+00:00 eob-250501a sshd[3638]: Received disconnect from 103.59.95.142 port 52318:11: Bye Bye [preauth]
2025-09-09T22:15:52.083079+00:00 eob-250501a sshd[3638]: Disconnected from authenticating user root 103.59.95.142 port 52318 [preauth]
2025-09-09T22:16:58.511319+00:00 eob-250501a sshd[4191]: Received disconnect from 117.53.46.76 port 39330:11: Bye Bye [preauth]
2025-09-09T22:16:58.513099+00:00 eob-250501a sshd[4191]: Disconnected from authenticating user root 117.53.46.76 port 39330 [preauth]
2025-09-09T22:17:01.962219+00:00 eob-250501a CRON[4193]: pam_unix(cron:session): session opened for user root(uid=0) by root(uid=0)
2025-09-09T22:17:14.246817+00:00 eob-250501a sshd[4204]: Received disconnect from 103.59.95.142 port 53776:11: Bye Bye [preauth]
2025-09-09T22:17:14.249561+00:00 eob-250501a sshd[4204]: Disconnected from authenticating user root 103.59.95.142 port 53776 [preauth]
2025-09-09T22:18:15.589856+00:00 eob-250501a sshd[4724]: Received disconnect from 117.53.46.76 port 58852:11: Bye Bye [preauth]
2025-09-09T22:18:15.592316+00:00 eob-250501a sshd[4724]: Disconnected from authenticating user root 117.53.46.76 port 58852 [preauth]
2025-09-09T22:18:42.530494+00:00 eob-250501a sshd[6687]: Received disconnect from 103.59.95.142 port 33630:11: Bye Bye [preauth]
2025-09-09T22:18:42.532181+00:00 eob-250501a sshd[6687]: Disconnected from authenticating user root 103.59.95.142 port 33630 [preauth]
2025-09-09T22:19:29.736074+00:00 eob-250501a sshd[7290]: Invalid user datascientist from 117.53.46.76 port 34250
2025-09-09T22:19:29.911546+00:00 eob-250501a sshd[7290]: Received disconnect from 117.53.46.76 port 34250:11: Bye Bye [preauth]
2025-09-09T22:19:29.912940+00:00 eob-250501a sshd[7290]: Disconnected from invalid user datascientist 117.53.46.76 port 34250 [preauth]

==> /var/log/batch_attacking_logs.log <==
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ingest_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ingest_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 170
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 170
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution


==> /var/log/batch_ip_geolocation.log <==
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 14, in <module>
    DB_HOST = os.getenv("DB_HOST", "localhost")
              ^^
NameError: name 'os' is not defined. Did you forget to import 'os'?

==> /var/log/batch_kern_logs.log <==
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 0
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 0
2025-08-24 18:30:03 [🔍]: No hay nuevas líneas en el log.

==> /var/log/cloud-init-output.log <==
ci-info: |   3   | 165.22.80.0 |   0.0.0.0   | 255.255.240.0 |    eth0   |   U   |
ci-info: +-------+-------------+-------------+---------------+-----------+-------+
ci-info: +++++++++++++++++++Route IPv6 info+++++++++++++++++++
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: | Route | Destination | Gateway | Interface | Flags |
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: |   0   |  fe80::/64  |    ::   |    eth0   |   U   |
ci-info: |   1   |  fe80::/64  |    ::   |    eth1   |   U   |
ci-info: |   3   |    local    |    ::   |    eth1   |   U   |
ci-info: |   4   |    local    |    ::   |    eth0   |   U   |
ci-info: |   5   |  multicast  |    ::   |    eth0   |   U   |
ci-info: |   6   |  multicast  |    ::   |    eth1   |   U   |
ci-info: +-------+-------------+---------+-----------+-------+
+ cloud-init-per instance do-resolved-conf /bin/false
+ exit 0
+ logger -t DigitalOcean adding random seed to /dev/urandom
+ base64 -d
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'modules:config' at Tue, 09 Sep 2025 22:12:25 +0000. Up 13.47 seconds.
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'modules:final' at Tue, 09 Sep 2025 22:12:31 +0000. Up 18.72 seconds.
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 finished at Tue, 09 Sep 2025 22:12:31 +0000. Datasource DataSourceConfigDrive [net,ver=2][source=/dev/vdb].  Up 18.84 seconds

==> /var/log/cloud-init.log <==
2025-09-09 22:12:31,349 - handlers.py[DEBUG]: start: modules-final/config-install_hotplug: running config-install_hotplug with frequency once-per-instance
2025-09-09 22:12:31,350 - helpers.py[DEBUG]: config-install_hotplug already ran (freq=once-per-instance)
2025-09-09 22:12:31,350 - handlers.py[DEBUG]: finish: modules-final/config-install_hotplug: SUCCESS: config-install_hotplug previously ran
2025-09-09 22:12:31,350 - modules.py[DEBUG]: Running module final_message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2025-09-09 22:12:31,350 - handlers.py[DEBUG]: start: modules-final/config-final_message: running config-final_message with frequency always
2025-09-09 22:12:31,350 - helpers.py[DEBUG]: Running config-final_message using lock (<cloudinit.helpers.DummyLock object at 0x7a09fbd9f2c0>)
2025-09-09 22:12:31,350 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-09-09 22:12:31,350 - util.py[DEBUG]: Reading 11 bytes from /proc/uptime
2025-09-09 22:12:31,365 - performance.py[DEBUG]: Rendering jinja2 template took 0.014 seconds
2025-09-09 22:12:31,365 - log_util.py[DEBUG]: Cloud-init v. 25.1.4-0ubuntu0~24.04.1 finished at Tue, 09 Sep 2025 22:12:31 +0000. Datasource DataSourceConfigDrive [net,ver=2][source=/dev/vdb].  Up 18.84 seconds
2025-09-09 22:12:31,365 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 69 bytes
2025-09-09 22:12:31,366 - handlers.py[DEBUG]: finish: modules-final/config-final_message: SUCCESS: config-final_message ran successfully and took 0.016 seconds
2025-09-09 22:12:31,366 - main.py[DEBUG]: Ran 10 modules with 0 failures
2025-09-09 22:12:31,366 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-09-09 22:12:31,366 - util.py[DEBUG]: Reading 11 bytes from /proc/uptime
2025-09-09 22:12:31,370 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmphy4iirn3) - w: [644] 535 bytes/chars
2025-09-09 22:12:31,371 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpfcyyomq5) - w: [644] 101 bytes/chars
2025-09-09 22:12:31,371 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-09-09 22:12:31,371 - performance.py[DEBUG]: cloud-init stage: 'modules-final' took 0.183 seconds
2025-09-09 22:12:31,371 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final

==> /var/log/configure_docker_limits.log <==
2025-09-09 22:13:24 [✅]: Docker está en ejecución.
2025-09-09 22:13:24 [🔍]: Verificando el contenedor f378768d0810...
2025-09-09 22:13:24 [⚙️]: Aplicando límites al contenedor f378768d0810...
f378768d0810
2025-09-09 22:13:24 [✅]: Límites aplicados correctamente a f378768d0810.
2025-09-09 22:13:24 [🔍]: Verificando el contenedor 56cb025684b3...
2025-09-09 22:13:24 [⚙️]: Aplicando límites al contenedor 56cb025684b3...
56cb025684b3
2025-09-09 22:13:24 [✅]: Límites aplicados correctamente a 56cb025684b3.
2025-09-09 22:13:24 [🔍]: Verificando el contenedor 07de94f6ee4c...
2025-09-09 22:13:24 [⚙️]: Aplicando límites al contenedor 07de94f6ee4c...
07de94f6ee4c
2025-09-09 22:13:24 [✅]: Límites aplicados correctamente a 07de94f6ee4c.
2025-09-09 22:13:24 [🔍]: Verificando el contenedor e8b3c91d5357...
2025-09-09 22:13:24 [⚙️]: Aplicando límites al contenedor e8b3c91d5357...
e8b3c91d5357
2025-09-09 22:13:24 [✅]: Límites aplicados correctamente a e8b3c91d5357.
2025-09-09 22:13:24 [🔍]: Verificando el contenedor 2845a26076ba...
2025-09-09 22:13:24 [ℹ️]: El contenedor 2845a26076ba ya tiene límites configurados.
2025-09-09 22:13:24 [🎯]: Proceso de configuración de límites completado.

==> /var/log/docker_resources.log <==
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'

==> /var/log/docker_resources_history.log <==
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | CONTAINER ID | MEM USAGE/LIMIT                  | SWAP USAGE/LIMIT                 | CPU USAGE/LIMIT               | NAME                                                             
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | 3c9ebefd8d2d | 51.32MiB / No definido (N/A %)   | 51.32MiB / No definido (N/A %)   | N/A % / No definido           | captain-captain.1.nqmy79ajr06glvpd8f51ggh49                      
dr-info: | 7f13309d6403 | 1.582MiB / 393 MiB (0.5 %)       | 1.582MiB / 786 MiB (0.3 %)       | N/A % / 100 MiliCores         | captain-certbot.1.m009zohpfl8zfk2w8isdqc5l0                      
dr-info: | 85e0f44c1489 | 0B / 393 MiB (0.0 %)             | 0B / 786 MiB (0.0 %)             | N/A % / 100 MiliCores         | captain-nginx.1.qtfkqqcyxtiq40dq9116b8zyo                        
dr-info: | 99aba7115a2a | 59.97MiB / 393 MiB (15.3 %)      | 59.97MiB / 786 MiB (7.6 %)       | N/A % / 100 MiliCores         | srv-captain--security250226app.1.gtcghw45t9o2im9q839g9dqjl       
dr-info: | 2845a26076ba | 7.27MiB / 393 MiB (1.8 %)        | 7.27MiB / 786 MiB (0.9 %)        | N/A % / 100 MiliCores         | data-container_data-container_1                                  
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: ===== 2025-08-24 18:30:01 =====
dr-info: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++Docker Resources+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | CONTAINER ID | MEM USAGE/LIMIT                  | SWAP USAGE/LIMIT                 | CPU USAGE/LIMIT               | NAME                                                             
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | d37816bebd3a | 1.617MiB / No definido (N/A %)   | 1.617MiB / No definido (N/A %)   | N/A % / No definido           | captain-certbot.1.00kqlkv25xs6gey72705immyq                      
dr-info: | 5b28c617fae9 | 2.707MiB / 393 MiB (0.8 %)       | 2.707MiB / 786 MiB (0.4 %)       | N/A % / 100 MiliCores         | captain-nginx.1.if8neg7tjaqcsuoksrmpfygih                        
dr-info: | 700d23dbd7e3 | 38.99MiB / 393 MiB (9.9 %)       | 38.99MiB / 786 MiB (5.0 %)       | N/A % / 100 MiliCores         | captain-captain.1.hxqcsby7v3gjfzu9h82xttpsp                      
dr-info: | 3612e9a401d3 | 56.09MiB / 393 MiB (14.2 %)      | 56.09MiB / 786 MiB (7.1 %)       | N/A % / 100 MiliCores         | srv-captain--security250226app.1.tmovpk0y629d30g34zif2rucr       
dr-info: | 2845a26076ba | 7.195MiB / 393 MiB (1.8 %)       | 7.195MiB / 786 MiB (0.9 %)       | N/A % / 100 MiliCores         | data-container_data-container_1                                  
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+

==> /var/log/dpkg.log <==
2025-09-06 06:36:48 startup archives unpack
2025-09-06 06:36:49 upgrade do-agent:amd64 3.16.11 3.18.2
2025-09-06 06:36:49 status half-configured do-agent:amd64 3.16.11
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.16.11
2025-09-06 06:36:49 status half-installed do-agent:amd64 3.16.11
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.18.2
2025-09-06 06:36:49 startup packages configure
2025-09-06 06:36:49 configure do-agent:amd64 3.18.2 <none>
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.18.2
2025-09-06 06:36:49 status half-configured do-agent:amd64 3.18.2
2025-09-06 06:36:50 status installed do-agent:amd64 3.18.2

==> /var/log/droplet-agent.update.log <==
Waiting 222 seconds

==> /var/log/fail2ban.log <==
2025-09-09 22:12:25,970 fail2ban.filter         [917]: INFO      findtime: 600
2025-09-09 22:12:25,970 fail2ban.actions        [917]: INFO      banTime: 3600
2025-09-09 22:12:25,970 fail2ban.filter         [917]: INFO      encoding: UTF-8
2025-09-09 22:12:25,970 fail2ban.jail           [917]: INFO    Creating new jail 'nginx-limit-req'
2025-09-09 22:12:25,970 fail2ban.jail           [917]: INFO    Jail 'nginx-limit-req' uses systemd {}
2025-09-09 22:12:25,991 fail2ban.jail           [917]: INFO    Initiated 'systemd' backend
2025-09-09 22:12:25,995 fail2ban.filtersystemd  [917]: INFO    [nginx-limit-req] Added journal match for: '_SYSTEMD_UNIT=nginx.service + _COMM=nginx'
2025-09-09 22:12:25,995 fail2ban.filter         [917]: INFO      maxRetry: 20
2025-09-09 22:12:25,995 fail2ban.filter         [917]: INFO      findtime: 60
2025-09-09 22:12:25,995 fail2ban.actions        [917]: INFO      banTime: 3600
2025-09-09 22:12:25,995 fail2ban.filter         [917]: INFO      encoding: UTF-8
2025-09-09 22:12:25,997 fail2ban.transmitter    [917]: ERROR   Jail 'nginx-badbots' skipped, because of wrong configuration: Unable to read the filter 'nginx-badbots'
2025-09-09 22:12:25,997 fail2ban.transmitter    [917]: ERROR   Jail 'nginx-noscript' skipped, because of wrong configuration: Unable to read the filter 'nginx-noscript'
2025-09-09 22:12:26,005 fail2ban.jail           [917]: INFO    Jail 'sshd' started
2025-09-09 22:12:26,013 fail2ban.jail           [917]: INFO    Jail 'nginx-http-auth' started
2025-09-09 22:12:26,022 fail2ban.jail           [917]: INFO    Jail 'nginx-limit-req' started
2025-09-09 22:12:26,337 fail2ban.filtersystemd  [917]: INFO    [nginx-limit-req] Jail is in operation now (process new journal entries)
2025-09-09 22:12:26,337 fail2ban.filtersystemd  [917]: INFO    [nginx-http-auth] Jail is in operation now (process new journal entries)
2025-09-09 22:12:26,797 fail2ban.filtersystemd  [917]: INFO    [sshd] Jail is in operation now (process new journal entries)
2025-09-09 22:19:30,056 fail2ban.filter         [917]: INFO    [sshd] Found 117.53.46.76 - 2025-09-09 22:19:29

==> /var/log/kern.log <==

==> /var/log/log_fail2ban_logs.log <==
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_fail2ban_batch.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_fail2ban_batch.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 230
2025-08-24 18:30:03 [⚡]: Líneas después del filtrado: 230
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 230
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution


==> /var/log/mail.log <==
