==> /var/log/alternatives.log <==

==> /var/log/apply_ssh_ratelimit.log <==

==> /var/log/apport.log <==

==> /var/log/auth.log <==
2025-09-10T18:45:01.377726+00:00 eob-250501a CRON[4086]: pam_unix(cron:session): session opened for user root(uid=0) by root(uid=0)
2025-09-10T18:45:01.383064+00:00 eob-250501a CRON[4086]: pam_unix(cron:session): session closed for user root
2025-09-10T18:45:12.445873+00:00 eob-250501a sshd[4089]: Received disconnect from 91.224.92.106 port 19034:11:  [preauth]
2025-09-10T18:45:12.447380+00:00 eob-250501a sshd[4089]: Disconnected from authenticating user root 91.224.92.106 port 19034 [preauth]
2025-09-10T18:45:36.210628+00:00 eob-250501a sshd[4097]: Invalid user squid from 116.99.168.51 port 55656
2025-09-10T18:45:36.388748+00:00 eob-250501a sshd[4097]: Connection closed by invalid user squid 116.99.168.51 port 55656 [preauth]
2025-09-10T18:46:01.924206+00:00 eob-250501a sshd[4104]: Accepted publickey for root from 91.126.43.112 port 16459 ssh2: RSA SHA256:YUDRPAU115MCwkF4S/wLFXV0Y7kLUTQ4QUL7H3Lc0ac
2025-09-10T18:46:01.927554+00:00 eob-250501a sshd[4104]: pam_unix(sshd:session): session opened for user root(uid=0) by root(uid=0)
2025-09-10T18:46:01.955253+00:00 eob-250501a systemd-logind[738]: New session 5 of user root.
2025-09-10T18:46:01.986802+00:00 eob-250501a (systemd): pam_unix(systemd-user:session): session opened for user root(uid=0) by root(uid=0)
2025-09-10T18:46:50.283252+00:00 eob-250501a sshd[4883]: Invalid user support from 116.99.168.51 port 37494
2025-09-10T18:47:00.714010+00:00 eob-250501a sshd[4887]: Invalid user config from 116.99.169.8 port 47480
2025-09-10T18:47:01.352597+00:00 eob-250501a sshd[4887]: Connection closed by invalid user config 116.99.169.8 port 47480 [preauth]
2025-09-10T18:48:58.419530+00:00 eob-250501a sshd[5463]: Connection closed by authenticating user root 116.99.169.8 port 42214 [preauth]
2025-09-10T18:50:01.392724+00:00 eob-250501a CRON[5779]: pam_unix(cron:session): session opened for user root(uid=0) by root(uid=0)
2025-09-10T18:50:02.974690+00:00 eob-250501a CRON[5779]: pam_unix(cron:session): session closed for user root
2025-09-10T18:50:25.774254+00:00 eob-250501a sshd[8007]: Invalid user admin from 116.99.169.8 port 47720
2025-09-10T18:50:25.959389+00:00 eob-250501a sshd[8007]: Connection closed by invalid user admin 116.99.169.8 port 47720 [preauth]
2025-09-10T18:50:40.224167+00:00 eob-250501a sshd[8136]: Received disconnect from 193.46.255.7 port 57586:11:  [preauth]
2025-09-10T18:50:40.224285+00:00 eob-250501a sshd[8136]: Disconnected from authenticating user root 193.46.255.7 port 57586 [preauth]

==> /var/log/batch_attacking_logs.log <==
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ingest_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ingest_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 170
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 170
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution


==> /var/log/batch_ip_geolocation.log <==
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 14, in <module>
    DB_HOST = os.getenv("DB_HOST", "localhost")
              ^^
NameError: name 'os' is not defined. Did you forget to import 'os'?

==> /var/log/batch_kern_logs.log <==
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 0
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 0
2025-08-24 18:30:03 [🔍]: No hay nuevas líneas en el log.

==> /var/log/cloud-init-output.log <==
ci-info: |   3   | 165.22.80.0 |   0.0.0.0   | 255.255.240.0 |    eth0   |   U   |
ci-info: +-------+-------------+-------------+---------------+-----------+-------+
ci-info: +++++++++++++++++++Route IPv6 info+++++++++++++++++++
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: | Route | Destination | Gateway | Interface | Flags |
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: |   0   |  fe80::/64  |    ::   |    eth0   |   U   |
ci-info: |   1   |  fe80::/64  |    ::   |    eth1   |   U   |
ci-info: |   3   |    local    |    ::   |    eth1   |   U   |
ci-info: |   4   |    local    |    ::   |    eth0   |   U   |
ci-info: |   5   |  multicast  |    ::   |    eth0   |   U   |
ci-info: |   6   |  multicast  |    ::   |    eth1   |   U   |
ci-info: +-------+-------------+---------+-----------+-------+
+ cloud-init-per instance do-resolved-conf /bin/false
+ exit 0
+ logger -t DigitalOcean adding random seed to /dev/urandom
+ base64 -d
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'modules:config' at Wed, 10 Sep 2025 18:39:53 +0000. Up 13.40 seconds.
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'modules:final' at Wed, 10 Sep 2025 18:39:59 +0000. Up 18.36 seconds.
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 finished at Wed, 10 Sep 2025 18:39:59 +0000. Datasource DataSourceConfigDrive [net,ver=2][source=/dev/vdb].  Up 18.47 seconds

==> /var/log/cloud-init.log <==
2025-09-10 18:39:59,581 - modules.py[DEBUG]: Running module install_hotplug (<module 'cloudinit.config.cc_install_hotplug' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_install_hotplug.py'>) with frequency once-per-instance
2025-09-10 18:39:59,581 - handlers.py[DEBUG]: start: modules-final/config-install_hotplug: running config-install_hotplug with frequency once-per-instance
2025-09-10 18:39:59,581 - helpers.py[DEBUG]: config-install_hotplug already ran (freq=once-per-instance)
2025-09-10 18:39:59,581 - handlers.py[DEBUG]: finish: modules-final/config-install_hotplug: SUCCESS: config-install_hotplug previously ran
2025-09-10 18:39:59,581 - modules.py[DEBUG]: Running module final_message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2025-09-10 18:39:59,582 - handlers.py[DEBUG]: start: modules-final/config-final_message: running config-final_message with frequency always
2025-09-10 18:39:59,582 - helpers.py[DEBUG]: Running config-final_message using lock (<cloudinit.helpers.DummyLock object at 0x7b65502c9910>)
2025-09-10 18:39:59,582 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-09-10 18:39:59,582 - util.py[DEBUG]: Reading 11 bytes from /proc/uptime
2025-09-10 18:39:59,592 - log_util.py[DEBUG]: Cloud-init v. 25.1.4-0ubuntu0~24.04.1 finished at Wed, 10 Sep 2025 18:39:59 +0000. Datasource DataSourceConfigDrive [net,ver=2][source=/dev/vdb].  Up 18.47 seconds
2025-09-10 18:39:59,593 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 69 bytes
2025-09-10 18:39:59,595 - handlers.py[DEBUG]: finish: modules-final/config-final_message: SUCCESS: config-final_message ran successfully and took 0.013 seconds
2025-09-10 18:39:59,595 - main.py[DEBUG]: Ran 10 modules with 0 failures
2025-09-10 18:39:59,595 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-09-10 18:39:59,595 - util.py[DEBUG]: Reading 11 bytes from /proc/uptime
2025-09-10 18:39:59,596 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmp9x1mj0yw) - w: [644] 534 bytes/chars
2025-09-10 18:39:59,596 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpj9gjur6j) - w: [644] 101 bytes/chars
2025-09-10 18:39:59,597 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-09-10 18:39:59,597 - performance.py[DEBUG]: cloud-init stage: 'modules-final' took 0.159 seconds
2025-09-10 18:39:59,597 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final

==> /var/log/configure_docker_limits.log <==
2025-09-10 18:50:01 [🚀]: Esperando a que Docker se inicie...
2025-09-10 18:50:01 [✅]: Docker está en ejecución.
2025-09-10 18:50:01 [🔍]: Verificando el contenedor ade9f6eb918d...
2025-09-10 18:50:02 [⚙️]: Aplicando límites al contenedor ade9f6eb918d...
ade9f6eb918d
2025-09-10 18:50:02 [✅]: Límites aplicados correctamente a ade9f6eb918d.
2025-09-10 18:50:02 [🔍]: Verificando el contenedor 0b3cd4a8d94e...
2025-09-10 18:50:02 [⚙️]: Aplicando límites al contenedor 0b3cd4a8d94e...
0b3cd4a8d94e
2025-09-10 18:50:02 [✅]: Límites aplicados correctamente a 0b3cd4a8d94e.
2025-09-10 18:50:02 [🔍]: Verificando el contenedor 92bc85f19223...
2025-09-10 18:50:02 [⚙️]: Aplicando límites al contenedor 92bc85f19223...
92bc85f19223
2025-09-10 18:50:02 [✅]: Límites aplicados correctamente a 92bc85f19223.
2025-09-10 18:50:02 [🔍]: Verificando el contenedor 4334726adcde...
2025-09-10 18:50:02 [ℹ️]: El contenedor 4334726adcde ya tiene límites configurados.
2025-09-10 18:50:02 [🔍]: Verificando el contenedor 2845a26076ba...
2025-09-10 18:50:02 [ℹ️]: El contenedor 2845a26076ba ya tiene límites configurados.
2025-09-10 18:50:02 [🎯]: Proceso de configuración de límites completado.

==> /var/log/docker_resources.log <==
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'

==> /var/log/docker_resources_history.log <==
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | CONTAINER ID | MEM USAGE/LIMIT                  | SWAP USAGE/LIMIT                 | CPU USAGE/LIMIT               | NAME                                                             
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | 3c9ebefd8d2d | 51.32MiB / No definido (N/A %)   | 51.32MiB / No definido (N/A %)   | N/A % / No definido           | captain-captain.1.nqmy79ajr06glvpd8f51ggh49                      
dr-info: | 7f13309d6403 | 1.582MiB / 393 MiB (0.5 %)       | 1.582MiB / 786 MiB (0.3 %)       | N/A % / 100 MiliCores         | captain-certbot.1.m009zohpfl8zfk2w8isdqc5l0                      
dr-info: | 85e0f44c1489 | 0B / 393 MiB (0.0 %)             | 0B / 786 MiB (0.0 %)             | N/A % / 100 MiliCores         | captain-nginx.1.qtfkqqcyxtiq40dq9116b8zyo                        
dr-info: | 99aba7115a2a | 59.97MiB / 393 MiB (15.3 %)      | 59.97MiB / 786 MiB (7.6 %)       | N/A % / 100 MiliCores         | srv-captain--security250226app.1.gtcghw45t9o2im9q839g9dqjl       
dr-info: | 2845a26076ba | 7.27MiB / 393 MiB (1.8 %)        | 7.27MiB / 786 MiB (0.9 %)        | N/A % / 100 MiliCores         | data-container_data-container_1                                  
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: ===== 2025-08-24 18:30:01 =====
dr-info: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++Docker Resources+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | CONTAINER ID | MEM USAGE/LIMIT                  | SWAP USAGE/LIMIT                 | CPU USAGE/LIMIT               | NAME                                                             
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | d37816bebd3a | 1.617MiB / No definido (N/A %)   | 1.617MiB / No definido (N/A %)   | N/A % / No definido           | captain-certbot.1.00kqlkv25xs6gey72705immyq                      
dr-info: | 5b28c617fae9 | 2.707MiB / 393 MiB (0.8 %)       | 2.707MiB / 786 MiB (0.4 %)       | N/A % / 100 MiliCores         | captain-nginx.1.if8neg7tjaqcsuoksrmpfygih                        
dr-info: | 700d23dbd7e3 | 38.99MiB / 393 MiB (9.9 %)       | 38.99MiB / 786 MiB (5.0 %)       | N/A % / 100 MiliCores         | captain-captain.1.hxqcsby7v3gjfzu9h82xttpsp                      
dr-info: | 3612e9a401d3 | 56.09MiB / 393 MiB (14.2 %)      | 56.09MiB / 786 MiB (7.1 %)       | N/A % / 100 MiliCores         | srv-captain--security250226app.1.tmovpk0y629d30g34zif2rucr       
dr-info: | 2845a26076ba | 7.195MiB / 393 MiB (1.8 %)       | 7.195MiB / 786 MiB (0.9 %)       | N/A % / 100 MiliCores         | data-container_data-container_1                                  
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+

==> /var/log/dpkg.log <==
2025-09-06 06:36:48 startup archives unpack
2025-09-06 06:36:49 upgrade do-agent:amd64 3.16.11 3.18.2
2025-09-06 06:36:49 status half-configured do-agent:amd64 3.16.11
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.16.11
2025-09-06 06:36:49 status half-installed do-agent:amd64 3.16.11
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.18.2
2025-09-06 06:36:49 startup packages configure
2025-09-06 06:36:49 configure do-agent:amd64 3.18.2 <none>
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.18.2
2025-09-06 06:36:49 status half-configured do-agent:amd64 3.18.2
2025-09-06 06:36:50 status installed do-agent:amd64 3.18.2

==> /var/log/droplet-agent.update.log <==
Waiting 748 seconds
Checking architecture support...OK
Preparing to check for update
Package Host: https://repos-droplet.digitalocean.com
Package Path: apt/droplet-agent/pool/main/main/d/droplet-agent/droplet-agent_
Keyring Path: apt/droplet-agent/pool/main/main/d/droplet-agent-keyring/droplet-agent-keyring_
Local Keyring:2.0.0
Local Version:1.2.11
Checking Latest Version...
Latest keyring package:2.0.0
Latest agent package:1.2.1
Updating droplet-agent deb package

==> /var/log/fail2ban.log <==
2025-09-10 18:39:54,224 fail2ban.filtersystemd  [925]: INFO    [nginx-http-auth] Jail is in operation now (process new journal entries)
2025-09-10 18:39:54,225 fail2ban.filtersystemd  [925]: INFO    [nginx-limit-req] Jail is in operation now (process new journal entries)
2025-09-10 18:39:54,695 fail2ban.filtersystemd  [925]: INFO    [sshd] Jail is in operation now (process new journal entries)
2025-09-10 18:40:02,779 fail2ban.filter         [925]: INFO    [sshd] Found 162.241.125.180 - 2025-09-10 18:40:02
2025-09-10 18:40:08,524 fail2ban.filter         [925]: INFO    [sshd] Found 193.228.139.220 - 2025-09-10 18:40:08
2025-09-10 18:40:21,918 fail2ban.filter         [925]: INFO    [sshd] Found 116.99.168.51 - 2025-09-10 18:40:21
2025-09-10 18:41:00,275 fail2ban.filter         [925]: INFO    [sshd] Found 162.241.125.180 - 2025-09-10 18:41:00
2025-09-10 18:41:00,774 fail2ban.filter         [925]: INFO    [sshd] Found 193.228.139.220 - 2025-09-10 18:41:00
2025-09-10 18:41:46,274 fail2ban.filter         [925]: INFO    [sshd] Found 80.94.95.15 - 2025-09-10 18:41:46
2025-09-10 18:41:51,968 fail2ban.filter         [925]: INFO    [sshd] Found 193.228.139.220 - 2025-09-10 18:41:51
2025-09-10 18:41:52,588 fail2ban.actions        [925]: NOTICE  [sshd] Ban 193.228.139.220
2025-09-10 18:41:56,274 fail2ban.filter         [925]: INFO    [sshd] Found 162.241.125.180 - 2025-09-10 18:41:55
2025-09-10 18:41:56,663 fail2ban.actions        [925]: NOTICE  [sshd] Ban 162.241.125.180
2025-09-10 18:43:19,918 fail2ban.filter         [925]: INFO    [sshd] Found 116.99.169.8 - 2025-09-10 18:43:19
2025-09-10 18:45:36,390 fail2ban.filter         [925]: INFO    [sshd] Found 116.99.168.51 - 2025-09-10 18:45:36
2025-09-10 18:46:50,524 fail2ban.filter         [925]: INFO    [sshd] Found 116.99.168.51 - 2025-09-10 18:46:50
2025-09-10 18:46:50,827 fail2ban.actions        [925]: NOTICE  [sshd] Ban 116.99.168.51
2025-09-10 18:47:01,024 fail2ban.filter         [925]: INFO    [sshd] Found 116.99.169.8 - 2025-09-10 18:47:00
2025-09-10 18:50:26,024 fail2ban.filter         [925]: INFO    [sshd] Found 116.99.169.8 - 2025-09-10 18:50:25
2025-09-10 18:50:26,156 fail2ban.actions        [925]: NOTICE  [sshd] Ban 116.99.169.8

==> /var/log/kern.log <==

==> /var/log/log_fail2ban_logs.log <==
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_fail2ban_batch.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_fail2ban_batch.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 230
2025-08-24 18:30:03 [⚡]: Líneas después del filtrado: 230
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 230
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution


==> /var/log/mail.log <==
