==> /var/log/alternatives.log <==

==> /var/log/apply_ssh_ratelimit.log <==

==> /var/log/apport.log <==

==> /var/log/auth.log <==
2025-09-11T17:54:41.269131+00:00 eob-250501a sshd[4127]: Invalid user userm from 118.194.230.231 port 47264
2025-09-11T17:54:41.527443+00:00 eob-250501a sshd[4127]: Received disconnect from 118.194.230.231 port 47264:11: Bye Bye [preauth]
2025-09-11T17:54:41.527550+00:00 eob-250501a sshd[4127]: Disconnected from invalid user userm 118.194.230.231 port 47264 [preauth]
2025-09-11T17:55:01.105857+00:00 eob-250501a CRON[4151]: pam_unix(cron:session): session opened for user root(uid=0) by root(uid=0)
2025-09-11T17:55:01.112938+00:00 eob-250501a CRON[4151]: pam_unix(cron:session): session closed for user root
2025-09-11T17:55:14.591095+00:00 eob-250501a sshd[4159]: Invalid user sshadmin from 194.0.234.93 port 28458
2025-09-11T17:55:14.645534+00:00 eob-250501a sshd[4159]: Connection closed by invalid user sshadmin 194.0.234.93 port 28458 [preauth]
2025-09-11T17:55:29.757496+00:00 eob-250501a sshd[4163]: Received disconnect from 193.46.255.99 port 51478:11:  [preauth]
2025-09-11T17:55:29.758495+00:00 eob-250501a sshd[4163]: Disconnected from authenticating user root 193.46.255.99 port 51478 [preauth]
2025-09-11T17:55:30.259009+00:00 eob-250501a sshd[4161]: Accepted publickey for root from 91.126.43.112 port 16510 ssh2: RSA SHA256:YUDRPAU115MCwkF4S/wLFXV0Y7kLUTQ4QUL7H3Lc0ac
2025-09-11T17:55:30.263510+00:00 eob-250501a sshd[4161]: pam_unix(sshd:session): session opened for user root(uid=0) by root(uid=0)
2025-09-11T17:55:30.303118+00:00 eob-250501a systemd-logind[739]: New session 5 of user root.
2025-09-11T17:55:30.354021+00:00 eob-250501a (systemd): pam_unix(systemd-user:session): session opened for user root(uid=0) by root(uid=0)
2025-09-11T17:55:39.812672+00:00 eob-250501a sshd[4448]: Invalid user username from 103.174.114.229 port 42668
2025-09-11T18:00:01.117988+00:00 eob-250501a CRON[6036]: pam_unix(cron:session): session opened for user root(uid=0) by root(uid=0)
2025-09-11T18:00:01.781262+00:00 eob-250501a CRON[6036]: pam_unix(cron:session): session closed for user root
2025-09-11T18:00:50.530286+00:00 eob-250501a sshd[6283]: Received disconnect from 193.46.255.103 port 56340:11:  [preauth]
2025-09-11T18:00:50.531536+00:00 eob-250501a sshd[6283]: Disconnected from authenticating user root 193.46.255.103 port 56340 [preauth]
2025-09-11T18:04:58.361649+00:00 eob-250501a sshd[9967]: Invalid user user from 194.0.234.93 port 33880
2025-09-11T18:04:58.422225+00:00 eob-250501a sshd[9967]: Connection closed by invalid user user 194.0.234.93 port 33880 [preauth]

==> /var/log/batch_attacking_logs.log <==
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ingest_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ingest_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 170
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 170
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution


==> /var/log/batch_ip_geolocation.log <==
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_ip_geolocation.py", line 14, in <module>
    DB_HOST = os.getenv("DB_HOST", "localhost")
              ^^
NameError: name 'os' is not defined. Did you forget to import 'os'?

==> /var/log/batch_kern_logs.log <==
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_kern_batch.py", line 10, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 0
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 0
2025-08-24 18:30:03 [🔍]: No hay nuevas líneas en el log.

==> /var/log/cloud-init-output.log <==
ci-info: |   3   | 165.22.80.0 |   0.0.0.0   | 255.255.240.0 |    eth0   |   U   |
ci-info: +-------+-------------+-------------+---------------+-----------+-------+
ci-info: +++++++++++++++++++Route IPv6 info+++++++++++++++++++
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: | Route | Destination | Gateway | Interface | Flags |
ci-info: +-------+-------------+---------+-----------+-------+
ci-info: |   0   |  fe80::/64  |    ::   |    eth0   |   U   |
ci-info: |   1   |  fe80::/64  |    ::   |    eth1   |   U   |
ci-info: |   3   |    local    |    ::   |    eth1   |   U   |
ci-info: |   4   |    local    |    ::   |    eth0   |   U   |
ci-info: |   5   |  multicast  |    ::   |    eth0   |   U   |
ci-info: |   6   |  multicast  |    ::   |    eth1   |   U   |
ci-info: +-------+-------------+---------+-----------+-------+
+ cloud-init-per instance do-resolved-conf /bin/false
+ exit 0
+ logger -t DigitalOcean adding random seed to /dev/urandom
+ base64 -d
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'modules:config' at Thu, 11 Sep 2025 17:49:27 +0000. Up 14.03 seconds.
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 running 'modules:final' at Thu, 11 Sep 2025 17:49:32 +0000. Up 19.30 seconds.
Cloud-init v. 25.1.4-0ubuntu0~24.04.1 finished at Thu, 11 Sep 2025 17:49:32 +0000. Datasource DataSourceConfigDrive [net,ver=2][source=/dev/vdb].  Up 19.39 seconds

==> /var/log/cloud-init.log <==
2025-09-11 17:49:32,898 - handlers.py[DEBUG]: start: modules-final/config-install_hotplug: running config-install_hotplug with frequency once-per-instance
2025-09-11 17:49:32,899 - helpers.py[DEBUG]: config-install_hotplug already ran (freq=once-per-instance)
2025-09-11 17:49:32,899 - handlers.py[DEBUG]: finish: modules-final/config-install_hotplug: SUCCESS: config-install_hotplug previously ran
2025-09-11 17:49:32,899 - modules.py[DEBUG]: Running module final_message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2025-09-11 17:49:32,899 - handlers.py[DEBUG]: start: modules-final/config-final_message: running config-final_message with frequency always
2025-09-11 17:49:32,899 - helpers.py[DEBUG]: Running config-final_message using lock (<cloudinit.helpers.DummyLock object at 0x74d902193c80>)
2025-09-11 17:49:32,899 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-09-11 17:49:32,899 - util.py[DEBUG]: Reading 11 bytes from /proc/uptime
2025-09-11 17:49:32,913 - performance.py[DEBUG]: Rendering jinja2 template took 0.013 seconds
2025-09-11 17:49:32,915 - log_util.py[DEBUG]: Cloud-init v. 25.1.4-0ubuntu0~24.04.1 finished at Thu, 11 Sep 2025 17:49:32 +0000. Datasource DataSourceConfigDrive [net,ver=2][source=/dev/vdb].  Up 19.39 seconds
2025-09-11 17:49:32,915 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 69 bytes
2025-09-11 17:49:32,916 - handlers.py[DEBUG]: finish: modules-final/config-final_message: SUCCESS: config-final_message ran successfully and took 0.017 seconds
2025-09-11 17:49:32,916 - main.py[DEBUG]: Ran 10 modules with 0 failures
2025-09-11 17:49:32,916 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2025-09-11 17:49:32,916 - util.py[DEBUG]: Reading 11 bytes from /proc/uptime
2025-09-11 17:49:32,917 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpe_5pkopv) - w: [644] 534 bytes/chars
2025-09-11 17:49:32,918 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmp3cfd2k9t) - w: [644] 101 bytes/chars
2025-09-11 17:49:32,918 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2025-09-11 17:49:32,918 - performance.py[DEBUG]: cloud-init stage: 'modules-final' took 0.151 seconds
2025-09-11 17:49:32,918 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final

==> /var/log/configure_docker_limits.log <==
2025-09-11 18:00:01 [🚀]: Esperando a que Docker se inicie...
2025-09-11 18:00:01 [✅]: Docker está en ejecución.
2025-09-11 18:00:01 [🔍]: Verificando el contenedor 1bee30c6cadf...
2025-09-11 18:00:01 [⚙️]: Aplicando límites al contenedor 1bee30c6cadf...
1bee30c6cadf
2025-09-11 18:00:01 [✅]: Límites aplicados correctamente a 1bee30c6cadf.
2025-09-11 18:00:01 [🔍]: Verificando el contenedor 8379292a68bd...
2025-09-11 18:00:01 [⚙️]: Aplicando límites al contenedor 8379292a68bd...
8379292a68bd
2025-09-11 18:00:01 [✅]: Límites aplicados correctamente a 8379292a68bd.
2025-09-11 18:00:01 [🔍]: Verificando el contenedor 0feee187cdef...
2025-09-11 18:00:01 [⚙️]: Aplicando límites al contenedor 0feee187cdef...
0feee187cdef
2025-09-11 18:00:01 [✅]: Límites aplicados correctamente a 0feee187cdef.
2025-09-11 18:00:01 [🔍]: Verificando el contenedor 7c002dffd261...
2025-09-11 18:00:01 [ℹ️]: El contenedor 7c002dffd261 ya tiene límites configurados.
2025-09-11 18:00:01 [🔍]: Verificando el contenedor 2845a26076ba...
2025-09-11 18:00:01 [ℹ️]: El contenedor 2845a26076ba ya tiene límites configurados.
2025-09-11 18:00:01 [🎯]: Proceso de configuración de límites completado.

==> /var/log/docker_resources.log <==
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'
Traceback (most recent call last):
  File "/usr/local/bin/docker_resources.py", line 5, in <module>
    from scripts.utils import log_info, send_email
ModuleNotFoundError: No module named 'scripts'

==> /var/log/docker_resources_history.log <==
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | CONTAINER ID | MEM USAGE/LIMIT                  | SWAP USAGE/LIMIT                 | CPU USAGE/LIMIT               | NAME                                                             
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | 3c9ebefd8d2d | 51.32MiB / No definido (N/A %)   | 51.32MiB / No definido (N/A %)   | N/A % / No definido           | captain-captain.1.nqmy79ajr06glvpd8f51ggh49                      
dr-info: | 7f13309d6403 | 1.582MiB / 393 MiB (0.5 %)       | 1.582MiB / 786 MiB (0.3 %)       | N/A % / 100 MiliCores         | captain-certbot.1.m009zohpfl8zfk2w8isdqc5l0                      
dr-info: | 85e0f44c1489 | 0B / 393 MiB (0.0 %)             | 0B / 786 MiB (0.0 %)             | N/A % / 100 MiliCores         | captain-nginx.1.qtfkqqcyxtiq40dq9116b8zyo                        
dr-info: | 99aba7115a2a | 59.97MiB / 393 MiB (15.3 %)      | 59.97MiB / 786 MiB (7.6 %)       | N/A % / 100 MiliCores         | srv-captain--security250226app.1.gtcghw45t9o2im9q839g9dqjl       
dr-info: | 2845a26076ba | 7.27MiB / 393 MiB (1.8 %)        | 7.27MiB / 786 MiB (0.9 %)        | N/A % / 100 MiliCores         | data-container_data-container_1                                  
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: ===== 2025-08-24 18:30:01 =====
dr-info: ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++Docker Resources+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | CONTAINER ID | MEM USAGE/LIMIT                  | SWAP USAGE/LIMIT                 | CPU USAGE/LIMIT               | NAME                                                             
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+
dr-info: | d37816bebd3a | 1.617MiB / No definido (N/A %)   | 1.617MiB / No definido (N/A %)   | N/A % / No definido           | captain-certbot.1.00kqlkv25xs6gey72705immyq                      
dr-info: | 5b28c617fae9 | 2.707MiB / 393 MiB (0.8 %)       | 2.707MiB / 786 MiB (0.4 %)       | N/A % / 100 MiliCores         | captain-nginx.1.if8neg7tjaqcsuoksrmpfygih                        
dr-info: | 700d23dbd7e3 | 38.99MiB / 393 MiB (9.9 %)       | 38.99MiB / 786 MiB (5.0 %)       | N/A % / 100 MiliCores         | captain-captain.1.hxqcsby7v3gjfzu9h82xttpsp                      
dr-info: | 3612e9a401d3 | 56.09MiB / 393 MiB (14.2 %)      | 56.09MiB / 786 MiB (7.1 %)       | N/A % / 100 MiliCores         | srv-captain--security250226app.1.tmovpk0y629d30g34zif2rucr       
dr-info: | 2845a26076ba | 7.195MiB / 393 MiB (1.8 %)       | 7.195MiB / 786 MiB (0.9 %)       | N/A % / 100 MiliCores         | data-container_data-container_1                                  
dr-info: +--------------+----------------------------------+----------------------------------+-------------------------------+--------------------------------------------------------------+

==> /var/log/dpkg.log <==
2025-09-06 06:36:48 startup archives unpack
2025-09-06 06:36:49 upgrade do-agent:amd64 3.16.11 3.18.2
2025-09-06 06:36:49 status half-configured do-agent:amd64 3.16.11
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.16.11
2025-09-06 06:36:49 status half-installed do-agent:amd64 3.16.11
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.18.2
2025-09-06 06:36:49 startup packages configure
2025-09-06 06:36:49 configure do-agent:amd64 3.18.2 <none>
2025-09-06 06:36:49 status unpacked do-agent:amd64 3.18.2
2025-09-06 06:36:49 status half-configured do-agent:amd64 3.18.2
2025-09-06 06:36:50 status installed do-agent:amd64 3.18.2

==> /var/log/droplet-agent.update.log <==
Waiting 748 seconds
Checking architecture support...OK
Preparing to check for update
Package Host: https://repos-droplet.digitalocean.com
Package Path: apt/droplet-agent/pool/main/main/d/droplet-agent/droplet-agent_
Keyring Path: apt/droplet-agent/pool/main/main/d/droplet-agent-keyring/droplet-agent-keyring_
Local Keyring:2.0.0
Local Version:1.2.11
Checking Latest Version...
Latest keyring package:2.0.0
Latest agent package:1.2.1
Updating droplet-agent deb package

==> /var/log/fail2ban.log <==
2025-09-11 17:49:27,496 fail2ban.actions        [928]: INFO      banTime: 3600
2025-09-11 17:49:27,496 fail2ban.filter         [928]: INFO      encoding: UTF-8
2025-09-11 17:49:27,497 fail2ban.transmitter    [928]: ERROR   Jail 'nginx-badbots' skipped, because of wrong configuration: Unable to read the filter 'nginx-badbots'
2025-09-11 17:49:27,497 fail2ban.transmitter    [928]: ERROR   Jail 'nginx-noscript' skipped, because of wrong configuration: Unable to read the filter 'nginx-noscript'
2025-09-11 17:49:27,506 fail2ban.jail           [928]: INFO    Jail 'sshd' started
2025-09-11 17:49:27,514 fail2ban.jail           [928]: INFO    Jail 'nginx-http-auth' started
2025-09-11 17:49:27,520 fail2ban.jail           [928]: INFO    Jail 'nginx-limit-req' started
2025-09-11 17:49:27,897 fail2ban.filtersystemd  [928]: INFO    [nginx-http-auth] Jail is in operation now (process new journal entries)
2025-09-11 17:49:27,902 fail2ban.filtersystemd  [928]: INFO    [nginx-limit-req] Jail is in operation now (process new journal entries)
2025-09-11 17:49:28,403 fail2ban.filtersystemd  [928]: INFO    [sshd] Jail is in operation now (process new journal entries)
2025-09-11 17:49:39,657 fail2ban.filter         [928]: INFO    [sshd] Found 103.174.114.229 - 2025-09-11 17:49:39
2025-09-11 17:49:57,179 fail2ban.filter         [928]: INFO    [sshd] Found 118.194.230.231 - 2025-09-11 17:49:56
2025-09-11 17:51:48,677 fail2ban.filter         [928]: INFO    [sshd] Found 195.178.110.133 - 2025-09-11 17:51:48
2025-09-11 17:52:24,126 fail2ban.filter         [928]: INFO    [sshd] Found 118.194.230.231 - 2025-09-11 17:52:23
2025-09-11 17:54:11,880 fail2ban.filter         [928]: INFO    [sshd] Found 103.174.114.229 - 2025-09-11 17:54:11
2025-09-11 17:54:41,528 fail2ban.filter         [928]: INFO    [sshd] Found 118.194.230.231 - 2025-09-11 17:54:41
2025-09-11 17:54:41,679 fail2ban.actions        [928]: NOTICE  [sshd] Ban 118.194.230.231
2025-09-11 17:55:14,929 fail2ban.filter         [928]: INFO    [sshd] Found 194.0.234.93 - 2025-09-11 17:55:14
2025-09-11 17:55:39,815 fail2ban.filter         [928]: INFO    [sshd] Found 103.174.114.229 - 2025-09-11 17:55:39
2025-09-11 17:55:39,972 fail2ban.actions        [928]: NOTICE  [sshd] Ban 103.174.114.229

==> /var/log/kern.log <==

==> /var/log/log_fail2ban_logs.log <==
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_fail2ban_batch.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
Traceback (most recent call last):
  File "/opt/monitoring/log_ingestor/log_fail2ban_batch.py", line 11, in <module>
    load_dotenv("/opt/monitoring/smtp_relay/.env")
    ^^^^^^^^^^^
NameError: name 'load_dotenv' is not defined
2025-08-24 18:30:03 [🚀]: Iniciando procesamiento de logs...
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution

2025-08-24 18:30:03 [📜]: Líneas obtenidas del log: 230
2025-08-24 18:30:03 [⚡]: Líneas después del filtrado: 230
2025-08-24 18:30:03 [📜]: Total de líneas obtenidas del log: 230
2025-08-24 18:30:03 [❌]: Error conectando a la base de datos: could not translate host name "srv-captain--security250226app" to address: Temporary failure in name resolution


==> /var/log/mail.log <==
